names:
- Pickup Truck
- Utility Truck
- Truck
- Cargo Truck
nc: 4
train: /Users/dfox/WPI/WPIClasses/DS598GraduateQualifyingProject/git/bae-systems-gqp-24/src/../preprocessed_datasets/data/baseline/train/tiling/640_640/100
val: /Users/dfox/WPI/WPIClasses/DS598GraduateQualifyingProject/git/bae-systems-gqp-24/src/../preprocessed_datasets/data/baseline/val/tiling/640_640/100
