names:
- Fixed-wing Aircraft
- Small Aircraft
- Cargo Plane
- Helicopter
nc: 4
train: ../preprocessed_datasets/data/baseline/train/tiling/640_640/100
val: ../preprocessed_datasets/data/degraded/val/tiling/640_640/100/640_640
