## Execution flow parameters
run_preprocess: true # default false
run_train: true # default false
run_knee_discovery: true # default false
generate_report: true # default false

#
#
# Global parameters
#
# top_dir: "/home/dcfox1/git/bae-systems-gqp-24" # top-level directory, can be full path, defaults to ../
# input_dir: "/home/dcfox1/pipeline_input" # input directory, can be full path, defaults to top_dir
# output_dir: "/home/dcfox1/pipeline_output" # output directory, can be full path, defaults to <top_dir>/<output_subdir>
#
# run_clean: true # default false, deletes the output directory

# Path to the data configuration file
data_config_filename: "data_config.yaml" # REQUIRED and MUST be either absolute path or based in the top_dir directory

# Subdirectory containing the input images
input_images_subdir: "xview_dataset_raw" # REQUIRED subdir from input_dir, CHANGED: used to be subdir from top_dir

# DEPRECATED, moved to preprocess
interim_images_subdir: "interim" # only used if preprocess:interim_subdir not defined

# Path to the input image labels
input_images_labels_filename: "xview_dataset_raw/xView_train.geojson" # REQUIRED inside input_dir

# Path to the class labels file
input_class_labels_filename: "xview_dataset_raw/xview_class_labels.json" # REQUIRED inside input_dir

# Directory for output results
output_subdir: "output" # CHANGED: DEPRECATED: subdir from top_dir, only used if output_dir not defined

# Model configuration
model: "yolov8m" # REQUIRED IF RUNNING PREPROCESSING OR TRAINING, name entry from models: in this file
use_cuda: true # Instructs all modules to use CUDA, default false

# Subdirectory for trained models
trained_models_subdir: "finetuned_models" # REQUIRED FOR TRAINING/FINE-TUNING

# Pixel size in meters
pixel_size: 0.3 # in meters

# Target labels for detection
target_labels: # REQUIRED FOR PREPROCESSING OR TRAINING, set of target labels to do detection on
   11: "Fixed-wing Aircraft"
   12: "Small Aircraft"
   13: "Cargo Plane"
   15: "Helicopter"
   17: "Passenger Vehicle"
   18: "Small Car"
   19: "Bus"
   20: "Pickup Truck"
   21: "Utility Truck"
   23: "Truck"
   24: "Cargo Truck"
   25: "Truck w/Box"
   26: "Truck Tractor"
   27: "Trailer"
   28: "Truck w/Flatbed"
   29: "Truck w/Liquid"
   32: "Crane Truck"
   33: "Railway Vehicle"
   34: "Passenger Car"
   35: "Cargo Car"
   36: "Flat Car"
   37: "Tank car"
   38: "Locomotive"
   40: "Maritime Vessel"
   41: "Motorboat"
   42: "Sailboat"
   44: "Tugboat"
   45: "Barge"
   47: "Fishing Vessel"
   49: "Ferry"
   50: "Yacht"
   51: "Container Ship"
   52: "Oil Tanker"
   53: "Engineering Vehicle"
   54: "Straddle Carrier"
   60: "Dump Truck"
   61: "Haul Truck"
   62: "Scraper/Tractor"
   63: "Front loader/Bulldozer"
   64: "Excavator"
   65: "Cement Mixer"
   66: "Ground Grader"

# #
# eval_method: "detection" # REQUIRED FOR PREPROCESSING, TRAINING OR KNEE DISCOVERY, whether to do detection or classification
# only "detection" is supported at this time

# Preprocessing method
preprocess_method: "tiling" # REQUIRED FOR PREPROCESSING, the preprocessing method from the supported value of
# Either "tiling" or "padding", reflected by the options in preprocess_methods below

#
# Module-specific parameters
#
preprocess:
  output_subdir: "preprocessed_datasets/data" # REQUIRED FOR PREPROCESSING, subdir from top_dir
  # interim_subdir: "preprocessed_datasets/interim" # REQUIRED FOR PREPROCESSING, subdir from top_dir
  filtered_labels_filename: "filtered_labels.json" # REQUIRED FOR PREPROCESSING, subdir from preprocess:output_subdir
  clean_subdir: true # wipes out the preprocess output_subdir, default false
  train_split: 0.8 # REQUIRED FOR PREPROCESSING

train:
  # clean_subdir: true # Code needs to be added for this
  output_subdir: "results" # REQUIRED FOR TRAIN AND GENERATE_REPORT, subdir for top_dir/<global output_subdir>
  hyperparameters_filename: "hyperparams.csv" # Filename to store the hyperparameters for final training
  fractional_factorial: true # default false

knee_discovery:
  output_subdir: "results" # REQUIRED FOR KNEE_DISCOVERY AND GENERATE_REPORT
  cache_results: true # Results are cached in memory to improve performance, default false
  use_eval_cache: true # Tells the evaluation method to use a cached model
  eval_results_filename: "iapc_results.csv" # REQUIRED, the accumulative results file, must be a csv
  clean_named_preprocess_subdir: 'degraded' # wipes out all degraded images, but not the baseline
  search_resolution_range: [0.05, 1.0] # REQUIRED, the search range of the fraction of the original resolution, rounded up
  search_resolution_step: 0.05 # REQUIRED, the steps for the range above

report:
  output_subdir: "reports" # REQUIRED FOR GENERATING REPORT
  clean_subdir: false # wipes out the reports output_subdir
  curves_per_graph: 3 # number of curves on each displayed graph, default is 5

#
# Supported preprocessing methods parameters
#
preprocess_methods: # REQUIRED FOR PREPROCESSING, at least one model MUST be specified and MUST match preprocess_method
  tiling:
    image_size: 640 # REQUIRED FOR TILING METHOD
    stride: 100 # REQUIRED FOR TILING METHOD
    train_baseline_subdir: "baseline/train/tiling/{maxwidth}_{maxheight}/{stride}" # REQUIRED FOR TILING METHOD
    val_baseline_subdir: "baseline/val/tiling/{maxwidth}_{maxheight}/{stride}" # REQUIRED FOR TILING METHOD
    train_degraded_subdir: "degraded/train/tiling/{maxwidth}_{maxheight}/{stride}/{effective_width}_{effective_height}"
    train_hyperparameter_subdir: "hyperparameter_tuning/train/tiling/{maxwidth}_{maxheight}/{stride}" # REQUIRED FOR HYPERPARAMETER TUNING
    val_hyperparameter_subdir: "hyperparameter_tuning/val/tiling/{maxwidth}_{maxheight}/{stride}" # REQUIRED FOR TILING METHOD
    val_degraded_subdir: "degraded/val/tiling/{maxwidth}_{maxheight}/{stride}/{effective_width}_{effective_height}"
    output_basename_append: "_{left_pixel_offset}_{top_pixel_offset}_{right_pixel_offset}_{bottom_pixel_offset}"
  padding:
    padsize: "max_square" # REQUIRED FOR PADDING METHOD
    image_size: 640 # REQUIRED FOR PADDING METHOD
    train_baseline_subdir: "baseline/train/padding/{maxwidth}_{maxheight}" # REQUIRED FOR PADDING METHOD
    val_baseline_subdir: "baseline/val/padding/{maxwidth}_{maxheight}" # REQUIRED FOR PADDING METHOD
    train_degraded_subdir: "degraded/train/padding/{maxwidth}_{maxheight}/{effective_width}_{effective_height}"
    val_degraded_subdir: "degraded/val/padding/{maxwidth}_{maxheight}/{effective_width}_{effective_height}"

models:
  yolov8m:
    name: "yolov8m"
    pretrained:
      library: "ultralytics"
      trained_name: "yolov8m"
    trained_model_filename: "yolov8m/model.pt"
    params:
      imgsz: 640 # REQUIRED FOR TRAINING/FINE-TUNING
      epochs: 50 # Number of epochs to use for training
      batch: 16
      freeze: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
    hyperparameters:
      cls: [1.0, 1.5]
      batch: [16]
      epochs: [50, 100]
